name: rest_now_test
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  syncfusion_localizations: ^28.2.6
  after_layout: ^1.2.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  faker: ^2.2.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^7.3.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_foreground: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans_bold.ttf
          weight: 700
